const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {Pool}=require('pg');
const ROOT=__dirname,PUBLIC=path.join(ROOT,'public'),DATA_DIR=process.env.DATA_DIR||path.join(ROOT,'data'),LEGACY_DB=path.join(DATA_DIR,'db.json'),SEED_DB=path.join(ROOT,'data','db.json');
if(!process.env.DATABASE_URL){console.error('DATABASE_URL орнатылмаған');process.exit(1)}
const pool=new Pool({connectionString:process.env.DATABASE_URL,max:20,idleTimeoutMillis:30000,connectionTimeoutMillis:10000});
const subjects=['Математика','Информатика','Физика','Химия','Биология','География','Қазақстан тарихы','Қазақ тілі мен әдебиеті','Орыс тілі мен әдебиеті','Қазақ мектебіндегі орыс тілі','Орыс мектебіндегі қазақ тілі','Ағылшын тілі'],sessions=new Map();
function out(res,status,data){res.writeHead(status,{'content-type':'application/json; charset=utf-8'});res.end(JSON.stringify(data))}
function body(req){return new Promise((ok,bad)=>{let s='';req.on('data',d=>{s+=d;if(s.length>15e6)req.destroy()});req.on('end',()=>{try{ok(s?JSON.parse(s):{})}catch(e){bad(e)}})})}
function token(req){return (req.headers.authorization||'').replace(/^Bearer /,'')}
function sessionSecret(){return process.env.SESSION_SECRET||process.env.ADMIN_PASSWORD||'MektepOlimp2026!'}
function issueSession(value,days=7){const payload=Buffer.from(JSON.stringify({value,exp:Date.now()+days*86400000})).toString('base64url'),sig=crypto.createHmac('sha256',sessionSecret()).update(payload).digest('base64url');return payload+'.'+sig}
function sessionValue(req){const t=token(req),old=sessions.get(t);if(old)return old;const [payload,sig]=t.split('.');if(!payload||!sig)return null;const expected=crypto.createHmac('sha256',sessionSecret()).update(payload).digest('base64url');if(sig.length!==expected.length||!crypto.timingSafeEqual(Buffer.from(sig),Buffer.from(expected)))return null;try{const x=JSON.parse(Buffer.from(payload,'base64url').toString());return x.exp>Date.now()?x.value:null}catch{return null}}
function admin(req){return sessionValue(req)==='admin'}
function cleanStudent(s){return {id:s.id,name:s.name,grade:Number(s.grade),subject:s.subject,code:s.code}}
function randomQuestionIds(items,limit){const a=items.map(q=>q.id);for(let i=a.length-1;i>0;i--){const j=crypto.randomInt(i+1);[a[i],a[j]]=[a[j],a[i]]}return a.slice(0,limit)}
function decodeHtml(s){return String(s||'').replace(/<[^>]*>/g,'').replace(/&nbsp;/g,' ').replace(/&amp;/g,'&').replace(/&lt;/g,'<').replace(/&gt;/g,'>').replace(/&#39;/g,"'").replace(/&quot;/g,'"').trim()}
function importedQuestion(row){const grade=Number(row[0]),subject=String(row[1]||'').trim(),text=String(row[2]||'').trim(),options=row.slice(3,7).map(x=>String(x||'').trim()),raw=String(row[7]??'').trim().toUpperCase(),correct=['A','B','C','D'].includes(raw)?'ABCD'.indexOf(raw):Number(raw)-1;if(![5,6,7,8,9,10,11].includes(grade)||!subjects.includes(subject)||!text||options.some(x=>!x)||correct<0||correct>3)return null;return {id:crypto.randomUUID(),grade,subject,text,options,correct,points:1,draft:false}}
function mapAttempt(a){return {id:a.id,studentId:a.student_id,startedAt:a.started_at,answers:a.answers||{},questionIds:a.question_ids||[],questionSnapshot:a.question_snapshot||[],violationCount:Number(a.violation_count)||0,proctorEvents:a.proctor_events||[],score:a.score,total:a.total,submittedAt:a.submitted_at}}
async function insertQuestions(client,questions){if(!questions.length)return;await client.query(`INSERT INTO questions(id,grade,subject,text,options,correct,points,draft) SELECT id,grade,subject,text,options,correct,points,COALESCE(draft,false) FROM jsonb_to_recordset($1::jsonb) AS x(id text,grade int,subject text,text text,options jsonb,correct int,points int,draft boolean) ON CONFLICT(id) DO NOTHING`,[JSON.stringify(questions)])}
async function initDb(){
  await pool.query(`CREATE TABLE IF NOT EXISTS app_settings(id boolean PRIMARY KEY DEFAULT true CHECK(id),data jsonb NOT NULL DEFAULT '{}'::jsonb);CREATE TABLE IF NOT EXISTS students(id text PRIMARY KEY,name text NOT NULL,grade int NOT NULL,subject text NOT NULL,code text NOT NULL UNIQUE,created_at timestamptz NOT NULL DEFAULT now());CREATE UNIQUE INDEX IF NOT EXISTS students_identity_idx ON students(lower(name),grade,subject);CREATE TABLE IF NOT EXISTS questions(id text PRIMARY KEY,grade int NOT NULL,subject text NOT NULL,text text NOT NULL,options jsonb NOT NULL,correct int NOT NULL,points int NOT NULL DEFAULT 1,draft boolean NOT NULL DEFAULT false);CREATE INDEX IF NOT EXISTS questions_pool_idx ON questions(grade,subject);CREATE TABLE IF NOT EXISTS attempts(id text PRIMARY KEY,student_id text NOT NULL REFERENCES students(id) ON DELETE CASCADE,started_at timestamptz NOT NULL DEFAULT now(),answers jsonb NOT NULL DEFAULT '{}'::jsonb,question_ids jsonb NOT NULL DEFAULT '[]'::jsonb,question_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb,violation_count int NOT NULL DEFAULT 0,proctor_events jsonb NOT NULL DEFAULT '[]'::jsonb,score int,total int,submitted_at timestamptz);ALTER TABLE attempts ADD COLUMN IF NOT EXISTS question_snapshot jsonb NOT NULL DEFAULT '[]'::jsonb;ALTER TABLE attempts ADD COLUMN IF NOT EXISTS violation_count int NOT NULL DEFAULT 0;ALTER TABLE attempts ADD COLUMN IF NOT EXISTS proctor_events jsonb NOT NULL DEFAULT '[]'::jsonb;CREATE UNIQUE INDEX IF NOT EXISTS attempts_one_per_student_idx ON attempts(student_id);CREATE INDEX IF NOT EXISTS attempts_submitted_idx ON attempts(submitted_at);`);
  const oldAttempts=(await pool.query("SELECT id,question_ids FROM attempts WHERE question_snapshot='[]'::jsonb AND jsonb_array_length(question_ids)>0")).rows;for(const a of oldAttempts){const ids=a.question_ids||[],rows=(await pool.query('SELECT * FROM questions WHERE id=ANY($1::text[])',[ids])).rows,byId=new Map(rows.map(q=>[q.id,q])),snapshot=ids.map(id=>byId.get(id)).filter(Boolean).map(q=>({id:q.id,text:q.text,options:q.options,correct:q.correct,points:q.points||1,grade:q.grade,subject:q.subject}));if(snapshot.length)await pool.query('UPDATE attempts SET question_snapshot=$1::jsonb WHERE id=$2',[JSON.stringify(snapshot),a.id])}
  const count=Number((await pool.query('SELECT COUNT(*) n FROM questions')).rows[0].n);let legacy=null;for(const f of [LEGACY_DB,SEED_DB]){try{if(fs.existsSync(f)){legacy=JSON.parse(fs.readFileSync(f,'utf8'));break}}catch(e){console.error('Ескі деректі оқу қатесі:',e.message)}}
  const client=await pool.connect();try{await client.query('BEGIN');await client.query('INSERT INTO app_settings(id,data) VALUES(true,$1::jsonb) ON CONFLICT(id) DO NOTHING',[JSON.stringify(legacy?.settings||{school:'Егемқұл Тасанбаев атындағы ЖББМ',durationMinutes:60})]);if(count===0&&legacy){for(const s of legacy.students||[])await client.query('INSERT INTO students(id,name,grade,subject,code,created_at) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(id) DO NOTHING',[s.id,s.name,s.grade,s.subject,s.code,s.createdAt||new Date()]);await insertQuestions(client,(legacy.questions||[]).map(q=>({...q,draft:!!q.draft})));for(const a of legacy.attempts||[])await client.query('INSERT INTO attempts(id,student_id,started_at,answers,question_ids,score,total,submitted_at) VALUES($1,$2,$3,$4::jsonb,$5::jsonb,$6,$7,$8) ON CONFLICT(id) DO NOTHING',[a.id,a.studentId,a.startedAt||new Date(),JSON.stringify(a.answers||{}),JSON.stringify(a.questionIds||[]),a.score??null,a.total??null,a.submittedAt||null])}await client.query('COMMIT')}catch(e){await client.query('ROLLBACK');throw e}finally{client.release()}console.log('PostgreSQL дайын')
}
async function settings(){const r=await pool.query('SELECT data FROM app_settings WHERE id=true');return r.rows[0]?.data||{durationMinutes:60}}
async function attemptQuestionRows(a){const ids=a.question_ids||[];let qs=a.question_snapshot||[];if(!qs.length&&ids.length){const qr=await pool.query('SELECT * FROM questions WHERE id=ANY($1::text[])',[ids]),byId=new Map(qr.rows.map(q=>[q.id,q]));qs=ids.map(id=>byId.get(id)).filter(Boolean).map(q=>({id:q.id,text:q.text,options:q.options,correct:q.correct,points:q.points||1,grade:q.grade,subject:q.subject}));if(qs.length)await pool.query('UPDATE attempts SET question_snapshot=$1::jsonb WHERE id=$2',[JSON.stringify(qs),a.id])}return qs}
async function finalizeAttempt(a,answers){const qs=await attemptQuestionRows(a);let score=0,total=0;for(const q of qs){total+=q.points||1;if(Number(answers?.[q.id])===Number(q.correct))score+=q.points||1}const saved=await pool.query('UPDATE attempts SET answers=$1::jsonb,score=$2,total=$3,submitted_at=COALESCE(submitted_at,now()) WHERE id=$4 RETURNING submitted_at',[JSON.stringify(answers||{}),score,total,a.id]);const review=qs.map(q=>{const selected=Number.isInteger(Number(answers?.[q.id]))?Number(answers[q.id]):null;return {id:q.id,text:q.text,options:q.options,selected,correct:Number(q.correct),isCorrect:selected===Number(q.correct)}});return {score,total,percent:total?Math.round(score/total*100):0,review,submittedAt:saved.rows[0]?.submitted_at}}
async function api(req,res,url){
  if(req.method==='GET'&&url.pathname==='/api/config')return out(res,200,{settings:await settings(),subjects,grades:[5,6,7,8,9,10,11]});
  if(req.method==='POST'&&url.pathname==='/api/student/register'){const b=await body(req),name=String(b.name||'').trim(),grade=Number(b.grade),subject=String(b.subject||'');if(!name||![5,6,7,8,9,10,11].includes(grade)||!subjects.includes(subject))return out(res,400,{error:'Мәліметтерді дұрыс толтырыңыз'});let r=await pool.query('SELECT * FROM students WHERE lower(name)=lower($1) AND grade=$2 AND subject=$3',[name,grade,subject]);if(!r.rows[0]){try{r=await pool.query('INSERT INTO students(id,name,grade,subject,code) VALUES($1,$2,$3,$4,$5) RETURNING *',[crypto.randomUUID(),name,grade,subject,'MO-'+Math.random().toString(36).slice(2,8).toUpperCase()])}catch(e){if(e.code==='23505')r=await pool.query('SELECT * FROM students WHERE lower(name)=lower($1) AND grade=$2 AND subject=$3',[name,grade,subject]);else throw e}}return out(res,200,cleanStudent(r.rows[0]))}
  if(req.method==='POST'&&url.pathname==='/api/student/login'){const b=await body(req),s=(await pool.query('SELECT * FROM students WHERE code=$1',[String(b.code||'').trim().toUpperCase()])).rows[0];if(!s)return out(res,401,{error:'Қатысу коды табылмады'});return out(res,200,{token:issueSession(s.id),student:cleanStudent(s)})}
  if(req.method==='GET'&&url.pathname==='/api/exam'){const sid=sessionValue(req),s=(await pool.query('SELECT * FROM students WHERE id=$1',[sid])).rows[0];if(!s)return out(res,401,{error:'Қайта кіріңіз'});if((await pool.query('SELECT 1 FROM attempts WHERE student_id=$1 AND submitted_at IS NOT NULL LIMIT 1',[sid])).rows[0])return out(res,409,{error:'Сіз тестті тапсырып қойдыңыз'});const bank=(await pool.query('SELECT * FROM questions WHERE grade=$1 AND subject=$2',[s.grade,s.subject])).rows;let a=(await pool.query('SELECT * FROM attempts WHERE student_id=$1 AND submitted_at IS NULL LIMIT 1',[sid])).rows[0];if(!a){const ids=randomQuestionIds(bank,25),byId=new Map(bank.map(q=>[q.id,q])),snapshot=ids.map(id=>byId.get(id)).filter(Boolean).map(q=>({id:q.id,text:q.text,options:q.options,correct:q.correct,points:q.points||1,grade:q.grade,subject:q.subject}));a=(await pool.query('INSERT INTO attempts(id,student_id,question_ids,question_snapshot) VALUES($1,$2,$3::jsonb,$4::jsonb) ON CONFLICT(student_id) DO UPDATE SET student_id=EXCLUDED.student_id RETURNING *',[crypto.randomUUID(),sid,JSON.stringify(ids),JSON.stringify(snapshot)])).rows[0]}let snapshot=a.question_snapshot||[];if(!snapshot.length){const ids=a.question_ids||[],byId=new Map(bank.map(q=>[q.id,q]));snapshot=ids.map(id=>byId.get(id)).filter(Boolean).map(q=>({id:q.id,text:q.text,options:q.options,correct:q.correct,points:q.points||1,grade:q.grade,subject:q.subject}));await pool.query('UPDATE attempts SET question_snapshot=$1::jsonb WHERE id=$2',[JSON.stringify(snapshot),a.id])}const qs=snapshot.map(({correct,...q})=>q);return out(res,200,{attemptId:a.id,student:cleanStudent(s),durationMinutes:(await settings()).durationMinutes,startedAt:a.started_at,answers:a.answers||{},violationCount:Number(a.violation_count)||0,questions:qs})}
  if(req.method==='POST'&&url.pathname==='/api/exam/save'){const sid=sessionValue(req),b=await body(req),a=(await pool.query('SELECT * FROM attempts WHERE id=$1 AND student_id=$2 AND submitted_at IS NULL',[b.attemptId,sid])).rows[0];if(!a)return out(res,409,{error:'Бұл тест аяқталған'});const chosen=new Set(a.question_ids||[]),valid={};for(const [id,value] of Object.entries(b.answers||{}))if(chosen.has(id)&&Number.isInteger(Number(value))&&Number(value)>=0&&Number(value)<=3)valid[id]=Number(value);await pool.query('UPDATE attempts SET answers=answers || $1::jsonb WHERE id=$2',[JSON.stringify(valid),a.id]);return out(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/exam/proctor'){const sid=sessionValue(req),b=await body(req),allowed=['page-hidden','face-missing','camera-denied','camera-off'],type=allowed.includes(b.type)?b.type:'unknown',counted=type==='page-hidden',event={type,at:new Date().toISOString(),detail:String(b.detail||'').slice(0,160)},r=await pool.query(`UPDATE attempts SET violation_count=violation_count+$1,proctor_events=proctor_events || $2::jsonb WHERE id=$3 AND student_id=$4 AND submitted_at IS NULL RETURNING *`,[counted?1:0,JSON.stringify([event]),b.attemptId,sid]),a=r.rows[0];if(!a)return out(res,409,{error:'Бұл тест аяқталған'});if(Number(a.violation_count)>=5){const result=await finalizeAttempt(a,a.answers||{});return out(res,200,{ended:true,violationCount:Number(a.violation_count),...result})}return out(res,200,{ended:false,violationCount:Number(a.violation_count)})}
  if(req.method==='POST'&&url.pathname==='/api/exam/submit'){const sid=sessionValue(req),b=await body(req),a=(await pool.query('SELECT * FROM attempts WHERE id=$1 AND student_id=$2 AND submitted_at IS NULL',[b.attemptId,sid])).rows[0];if(!a)return out(res,409,{error:'Бұл тест жіберілген'});return out(res,200,await finalizeAttempt(a,b.answers||{}))}
  if(req.method==='POST'&&url.pathname==='/api/admin/login'){const b=await body(req),adminPassword=process.env.ADMIN_PASSWORD||'Mektep2026!';if(b.login!=='admin'||b.password!==adminPassword)return out(res,401,{error:'Логин немесе құпиясөз қате'});return out(res,200,{token:issueSession('admin',1)})}
  if(url.pathname.startsWith('/api/admin/')&&!admin(req))return out(res,401,{error:'Әкімші ретінде кіріңіз'});
  if(req.method==='GET'&&url.pathname==='/api/admin/dashboard'){const [st,sr,qr,ar]=await Promise.all([settings(),pool.query('SELECT * FROM students ORDER BY created_at'),pool.query('SELECT * FROM questions ORDER BY grade,subject'),pool.query('SELECT * FROM attempts ORDER BY started_at')]);return out(res,200,{settings:st,students:sr.rows.map(cleanStudent),questions:qr.rows,attempts:ar.rows.map(mapAttempt)})}
  if(req.method==='DELETE'&&url.pathname==='/api/admin/participants'){const c=await pool.connect();try{await c.query('BEGIN');const attempts=Number((await c.query('SELECT COUNT(*) n FROM attempts')).rows[0].n),students=Number((await c.query('SELECT COUNT(*) n FROM students')).rows[0].n);await c.query('DELETE FROM students');await c.query('COMMIT');return out(res,200,{ok:true,removedStudents:students,removedAttempts:attempts})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
  if(req.method==='POST'&&url.pathname==='/api/admin/questions'){const b=await body(req);if(!b.text||!Array.isArray(b.options)||b.options.length<2)return out(res,400,{error:'Сұрақ толық емес'});await insertQuestions(pool,[{id:crypto.randomUUID(),grade:Number(b.grade),subject:b.subject,text:b.text,options:b.options,correct:Number(b.correct),points:Number(b.points)||1,draft:false}]);return out(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/admin/questions/import'){const b=await body(req),name=String(b.name||'').toLowerCase(),buf=Buffer.from(String(b.data||''),'base64');if(!buf.length||buf.length>10e6)return out(res,400,{error:'Файл бос немесе 10 МБ-тан үлкен'});let rows=[];if(name.endsWith('.xlsx')||name.endsWith('.xls')){const XLSX=require('xlsx'),book=XLSX.read(buf,{type:'buffer'}),sheet=book.Sheets[book.SheetNames[0]];rows=XLSX.utils.sheet_to_json(sheet,{header:1,defval:''}).slice(1)}else if(name.endsWith('.docx')){const mammoth=require('mammoth'),html=(await mammoth.convertToHtml({buffer:buf})).value;rows=[...html.matchAll(/<tr[^>]*>([\s\S]*?)<\/tr>/gi)].map(m=>[...m[1].matchAll(/<t[dh][^>]*>([\s\S]*?)<\/t[dh]>/gi)].map(c=>decodeHtml(c[1]))).slice(1)}else return out(res,400,{error:'Тек .xlsx, .xls немесе .docx файлын таңдаңыз'});const questions=rows.slice(0,5000).map(importedQuestion).filter(Boolean);if(!questions.length)return out(res,400,{error:'Жарамды сұрақ табылмады. Бағандар: Сынып, Пән, Сұрақ, A, B, C, D, Дұрыс жауап'});await insertQuestions(pool,questions);return out(res,200,{count:questions.length,skipped:rows.length-questions.length})}
  if(req.method==='POST'&&url.pathname==='/api/admin/ai-generate'){if(!process.env.GEMINI_API_KEY)return out(res,400,{error:'GEMINI_API_KEY орнатылмаған'});const b=await body(req),grade=Number(b.grade),subject=String(b.subject||''),count=Math.min(30,Math.max(1,Number(b.count)||5)),language=b.language==='ru'?'орыс':'қазақ';if(![5,6,7,8,9,10,11].includes(grade)||!subjects.includes(subject))return out(res,400,{error:'Сынып пен пәнді таңдаңыз'});const schema={type:'object',properties:{questions:{type:'array',minItems:count,maxItems:count,items:{type:'object',properties:{text:{type:'string'},options:{type:'array',minItems:4,maxItems:4,items:{type:'string'}},correct:{type:'integer',minimum:0,maximum:3},explanation:{type:'string'}},required:['text','options','correct','explanation'],additionalProperties:false}}},required:['questions'],additionalProperties:false},prompt=`Қазақстан мектебінің ${grade}-сыныбына арналған ${subject} пәнінен ${count} олимпиадалық тест сұрағын ${language} тілінде құрастыр. Оқу бағдарламасына сай, бірмәнді, жас ерекшелігіне лайық болсын. Әр сұрақта 4 нұсқа және бір ғана дұрыс жауап болсын.`,model=process.env.GEMINI_MODEL||'gemini-2.5-flash',endpoint=`https://generativelanguage.googleapis.com/v1beta/models/${encodeURIComponent(model)}:generateContent`,rr=await fetch(endpoint,{method:'POST',headers:{'x-goog-api-key':process.env.GEMINI_API_KEY,'content-type':'application/json'},body:JSON.stringify({contents:[{role:'user',parts:[{text:prompt}]}],generationConfig:{responseMimeType:'application/json',responseJsonSchema:schema,temperature:0.4}})}),data=await rr.json();if(!rr.ok)return out(res,502,{error:data.error?.message||'Gemini қызметі жауап бермеді'});const txt=data.candidates?.[0]?.content?.parts?.map(x=>x.text||'').join('');let parsed;try{parsed=JSON.parse(txt)}catch(e){return out(res,502,{error:'Gemini жауабын оқу мүмкін болмады'})}const generated=(parsed.questions||[]).map(q=>({...q,id:crypto.randomUUID(),grade,subject,points:1,draft:true}));await insertQuestions(pool,generated);return out(res,200,{count:generated.length,questions:generated})}
  if(req.method==='DELETE'&&url.pathname.startsWith('/api/admin/questions/')){await pool.query('DELETE FROM questions WHERE id=$1',[url.pathname.split('/').pop()]);return out(res,200,{ok:true})}
  if(req.method==='POST'&&url.pathname==='/api/admin/settings'){const b=await body(req);if(b.durationMinutes!==undefined)b.durationMinutes=Number(b.durationMinutes)||60;const r=await pool.query('UPDATE app_settings SET data=data || $1::jsonb WHERE id=true RETURNING data',[JSON.stringify(b)]);return out(res,200,r.rows[0].data)}
  return out(res,404,{error:'Табылмады'});
}
const mime={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.json':'application/json','.svg':'image/svg+xml','.ico':'image/x-icon','.png':'image/png'};
async function start(){await initDb();http.createServer(async(req,res)=>{try{const url=new URL(req.url,'http://localhost');if(url.pathname==='/health'){await pool.query('SELECT 1');res.writeHead(200,{'content-type':'text/plain'});return res.end('ok')}if(url.pathname.startsWith('/api/'))return await api(req,res,url);let f=path.join(PUBLIC,url.pathname==='/'?'index.html':url.pathname);if(!f.startsWith(PUBLIC)||!fs.existsSync(f)||fs.statSync(f).isDirectory()){res.writeHead(404);return res.end('Not found')}const ext=path.extname(f),fresh=['.html','.js','.css'].includes(ext);res.writeHead(200,{'content-type':mime[ext]||'application/octet-stream','cache-control':fresh?'no-cache, no-store, must-revalidate':'public, max-age=3600'});fs.createReadStream(f).pipe(res)}catch(e){console.error(e);out(res,500,{error:'Сервер қатесі'})}}).listen(process.env.PORT||3000,'0.0.0.0',()=>console.log('MektepOlimpiada: http://localhost:'+(process.env.PORT||3000)))}
start().catch(e=>{console.error('Іске қосу қатесі:',e);process.exit(1)});
